// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//

/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="BeagleBeaglePort", Namespace="urn:ActionWebService")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapInclude(typeof(Item))]
public class BeagleService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public BeagleService() {
        this.Url = "http://localhost:3000/beagle/api";
    }
    
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("/beagle/api/ExecuteWithOrder", RequestNamespace="urn:ActionWebService", ResponseNamespace="urn:ActionWebService")]
    [return: System.Xml.Serialization.SoapElement("return")]
    public Search ExecuteWithOrder(string query, string order) {
        object[] results = this.Invoke("ExecuteWithOrder", new object[] {
            query,
            order});
        return ((Search)(results[0]));
    }
    
    public System.IAsyncResult BeginExecuteWithOrder(string query, string order, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ExecuteWithOrder", new object[] {
            query,
            order}, callback, asyncState);
    }
    
    public Search EndExecuteWithOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Search)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("/beagle/api/Execute", RequestNamespace="urn:ActionWebService", ResponseNamespace="urn:ActionWebService")]
    [return: System.Xml.Serialization.SoapElement("return")]
    public Search Execute(string query) {
        object[] results = this.Invoke("Execute", new object[] {
            query});
        return ((Search)(results[0]));
    }
    
    public System.IAsyncResult BeginExecute(string query, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Execute", new object[] {
            query}, callback, asyncState);
    }
    
    public Search EndExecute(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Search)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapType(Namespace="urn:ActionWebService")]
public class Search {
    
    /// <remarks/>
    public System.Double first_hit;
    
    /// <remarks/>
    public System.Double total_time;
    
    /// <remarks/>
    public string order;
    
    /// <remarks/>
    public int number_of_hits;
    
    /// <remarks/>
    public Item[] results;
    
    /// <remarks/>
    public string key;
}

/// <remarks/>
[System.Xml.Serialization.SoapType(Namespace="urn:ActionWebService")]
public class Item {
    
    /// <remarks/>
    public string divers;
    
    /// <remarks/>
    public string uri;
    
    /// <remarks/>
    public string mime_type;
    
    /// <remarks/>
    public string type;
    
    /// <remarks/>
    public System.DateTime time;
    
    /// <remarks/>
    public string pa_uri;
    
    /// <remarks/>
    public string source;
    
    /// <remarks/>
    public string snip;
}

